# Generated by Django 6.0.2 on 2026-03-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_document',
            field=models.TextField(blank=True, help_text='Texte du bail (rédaction et mise à jour des clauses)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Si renseigné, le bien est archivé', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ENTRY', 'Entrée'), ('EXIT', 'Sortie')], max_length=10)),
                ('report_date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Observations, état des pièces, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='rental.lease')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
