# Generated by Django 6.0.2 on 2026-03-07 17:29

import django.db.models.deletion
from django.db import migrations, models


def copy_tenant_to_tenants(apps, schema_editor):
    Lease = apps.get_model("rental", "Lease")
    for lease in Lease.objects.filter(tenant__isnull=False):
        lease.tenants.add(lease.tenant_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_add_lease_document_inspection_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Un ou plusieurs locataires (colocation possible).', related_name='lease_set', to='rental.tenant'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text="Déprécié : utiliser 'tenants'. Conservé pour migration.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rental.tenant'),
        ),
        migrations.RunPython(copy_tenant_to_tenants, noop),
    ]
