# Generated by Django 6.0.2 on 2026-03-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_add_tenants_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Un ou plusieurs locataires (colocation possible).', related_name='leases', to='rental.tenant'),
        ),
    ]
