# Generated by Django 5.2.12 on 2026-03-08 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionreport',
            options={'ordering': ['-report_date'], 'verbose_name': 'État des lieux', 'verbose_name_plural': 'États des lieux'},
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['-start_date'], 'verbose_name': 'Bail', 'verbose_name_plural': 'Baux'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name': 'Bien', 'verbose_name_plural': 'Biens'},
        ),
        migrations.AlterModelOptions(
            name='rentinvoice',
            options={'ordering': ['-due_date'], 'verbose_name': 'Loyer', 'verbose_name_plural': 'Loyers'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Locataire', 'verbose_name_plural': 'Locataires'},
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du modèle (ex : État des lieux type)', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Texte type (sections, points à vérifier). Vous pouvez le modifier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Modèle d'état des lieux",
                'verbose_name_plural': "Modèles d'état des lieux",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du modèle (ex : Bail type 3 ans)', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Texte type du bail. Vous pouvez le modifier selon vos besoins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de bail',
                'verbose_name_plural': 'Modèles de bail',
                'ordering': ['name'],
            },
        ),
    ]
