# Generated by Django 5.2.12 on 2026-03-08 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_stripe_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'organisation (ex : SCI Dupont)", max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(help_text='Utilisateur ayant créé le bien (conservé pour historique).', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(help_text='Utilisateur ayant créé le locataire.', on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_templates', to='rental.organisation'),
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_templates', to='rental.organisation'),
        ),
        migrations.AddField(
            model_name='property',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation à laquelle appartient le bien (accès multi-utilisateurs).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rental.organisation'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='rental.organisation'),
        ),
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('member', 'Membre')], default='member', max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rental.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisation",
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
