# Generated by Django 5.2.12 on 2026-03-08 20:02

import django.db.models.deletion
import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rental', '0010_announcements_admin_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('landlord', 'Bailleur'), ('tenant', 'Locataire')], max_length=20)),
                ('email', models.EmailField(help_text='Email auquel le lien de signature est envoyé.', max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, help_text='Locataire concerné (pour rôle locataire).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_invitations', to='rental.tenant')),
            ],
            options={
                'verbose_name': 'Invitation à signer',
                'verbose_name_plural': 'Invitations à signer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(max_length=200, verbose_name='Nom du signataire')),
                ('signature_image', models.ImageField(help_text='Image PNG de la signature dessinée.', upload_to=rental.models.signature_upload_path, verbose_name='Signature (image)')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='rental.signinginvitation')),
            ],
            options={
                'verbose_name': 'Signature de document',
                'verbose_name_plural': 'Signatures de documents',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signinginvitation',
            index=models.Index(fields=['content_type', 'object_id'], name='rental_sign_content_6cf495_idx'),
        ),
    ]
