# Generated by Django 5.2.12 on 2026-03-08 20:29

import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_electronic_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsignature',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Optionnel ; non utilisé en mode validation simple.', null=True, upload_to=rental.models.signature_upload_path, verbose_name='Signature (image)'),
        ),
    ]
