# Generated by Django 5.2.12 on 2026-03-08 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_signature_image_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Compte courant BNP', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='rental.organisation')),
                ('owner', models.ForeignKey(help_text="Propriétaire du compte (si pas d'organisation).", on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant (positif = entrée, négatif = sortie)', max_digits=12)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rental.bankaccount')),
                ('rent_invoice', models.ForeignKey(blank=True, help_text='Loyer rapproché avec cette opération.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='rental.rentinvoice')),
            ],
            options={
                'verbose_name': 'Opération bancaire',
                'verbose_name_plural': 'Opérations bancaires',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
