# Generated by Django 5.2.12 on 2026-03-08 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rental', '0014_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag bien',
                'verbose_name_plural': 'Tags biens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('letter_type', models.CharField(choices=[('MISE_EN_DEMEURE', 'Mise en demeure'), ('RESILIATION', 'Résiliation'), ('AVENANT', 'Avenant'), ('PREAVIS', 'Préavis')], max_length=30)),
                ('content', models.TextField(help_text='Variables : {{tenant}}, {{property}}, {{address}}, {{rent}}, {{due_date}}, {{landlord_name}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to='rental.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de lettre',
                'verbose_name_plural': 'Modèles de lettre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_type', models.CharField(choices=[('DPE', 'DPE'), ('AMIANTE', 'Amiante'), ('ELECTRICITE', 'Électricité'), ('GAZ', 'Gaz'), ('ERGONOMIE', 'Ergonomie')], max_length=20)),
                ('done_date', models.DateField(help_text='Date du diagnostic')),
                ('expiry_date', models.DateField(blank=True, help_text='Date de fin de validité', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='rental.property')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
                'ordering': ['-expiry_date', '-done_date'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags pour filtrer (LMNP, meublé, etc.).', related_name='properties', to='rental.propertytag'),
        ),
        migrations.CreateModel(
            name='StoredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BAIL', 'Bail'), ('QUITTANCE', 'Quittance'), ('ETAT_LIEUX', 'État des lieux'), ('LETTRE', 'Lettre'), ('OTHER', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_documents', to='rental.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_documents', to='rental.tenant')),
            ],
            options={
                'verbose_name': 'Document stocké',
                'verbose_name_plural': 'Documents stockés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to='rental.tenant')),
            ],
            options={
                'verbose_name': 'Accès portail locataire',
                'verbose_name_plural': 'Accès portail locataire',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL qui recevra les POST', max_length=500)),
                ('event_types', models.CharField(help_text='Événements (séparés par des virgules) : rent_paid, lease_ended, invoice_created, etc.', max_length=500)),
                ('secret', models.CharField(blank=True, help_text='Clé pour signer le payload', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='rental.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_after_due', models.PositiveSmallIntegerField(help_text="Jours après l'échéance (ex : 7, 15, 30)")),
                ('email_subject', models.CharField(default='Rappel – loyer à régler', max_length=200)),
                ('email_body_template', models.TextField(blank=True, help_text='Corps du mail. Variables : {{tenant}}, {{amount}}, {{due_date}}, {{property}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='rental.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règle de relance',
                'verbose_name_plural': 'Règles de relance',
                'ordering': ['days_after_due'],
                'unique_together': {('owner', 'days_after_due')},
            },
        ),
    ]
