# Generated by Django 5.2.12 on 2026-03-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_premium_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_annual',
            field=models.CharField(blank=True, help_text='ID du prix Stripe annuel (price_xxx)', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID du prix Stripe mensuel (price_xxx)', max_length=100),
        ),
    ]
