# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0016_plan_annual_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="dpe_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non renseigné"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                help_text="Classe énergétique du DPE (A à G).",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="dpe_valid_until",
            field=models.DateField(
                blank=True,
                help_text="Date de fin de validité du DPE (optionnel, ex. validité 10 ans).",
                null=True,
            ),
        ),
    ]
