# Generated by Django 5.2.12 on 2026-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_lease_inspection_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='content',
            field=models.TextField(help_text='Variables : {{locataire}}, {{bien}}, {{adresse}}, {{loyer}}, {{echeance}}, {{nom_bailleur}}'),
        ),
    ]
