# Generated by Django 5.2.12 on 2026-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_letter_template_variables_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='content',
            field=models.TextField(help_text='Texte du modèle ; les modèles types illustrent les champs dynamiques disponibles.'),
        ),
    ]
