# Generated by Django 5.2.12 on 2026-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_letter_template_help_text_simplify'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinvoice',
            name='late_reminder_last_days_after_due',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dernier palier de relance envoyé (7, 15 ou 30 = J+N après échéance)', null=True),
        ),
    ]
