# Generated by Django 5.2.12 on 2026-03-22 17:45

import django.core.validators
import django.db.models.deletion
import rental.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_rentinvoice_late_reminder_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(help_text='Email de réponse pour le staff', max_length=254)),
                ('theme', models.CharField(choices=[('ux', 'Expérience utilisateur (UX)'), ('performance', 'Performance technique'), ('content', 'Contenu & conversion'), ('seo', 'Référencement (SEO)')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggestion utilisateur',
                'verbose_name_plural': 'Suggestions utilisateur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSuggestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=rental.models.user_suggestion_attachment_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'txt'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rental.usersuggestion')),
            ],
            options={
                'verbose_name': 'Pièce jointe (suggestion)',
                'verbose_name_plural': 'Pièces jointes (suggestions)',
            },
        ),
    ]
