# Generated by Django 5.2.12 on 2026-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_user_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestion',
            name='theme',
            field=models.CharField(choices=[('ux', 'Expérience utilisateur (UX)'), ('performance', 'Performance technique'), ('content', 'Contenu & conversion'), ('seo', 'Référencement (SEO)'), ('other', 'Autres')], max_length=20),
        ),
    ]
