# Generated by Django 5.2.12 on 2026-03-28 13:12

import django.core.validators
import django.db.models.deletion
import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_plan_clear_duplicate_stripe_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='shared_with_portal',
            field=models.BooleanField(default=False, help_text='Si coché, le locataire peut télécharger ce PDF depuis son portail (lien sécurisé).'),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_renewal_reminder_date',
            field=models.DateField(blank=True, help_text='Date à rappeler au locataire (ex. échéance de reconduction ou fin de préavis).', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='portal_payment_url',
            field=models.URLField(blank=True, help_text='Lien optionnel de paiement en ligne (Stripe Payment Link, Lydia, etc.) affiché aux locataires dans le portail.', max_length=500),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_insurance_valid_until',
            field=models.DateField(blank=True, help_text="Fin de validité de l'assurance habitation du locataire (rappel dans le portail).", null=True),
        ),
        migrations.AddField(
            model_name='storeddocument',
            name='shared_with_portal',
            field=models.BooleanField(default=False, help_text='Le locataire concerné (ou lié au bien du bail) pourra télécharger ce fichier depuis son portail.', verbose_name='Visible sur le portail locataire'),
        ),
        migrations.AlterField(
            model_name='storeddocument',
            name='document_type',
            field=models.CharField(choices=[('BAIL', 'Bail'), ('QUITTANCE', 'Quittance'), ('ETAT_LIEUX', 'État des lieux'), ('AVENANT', 'Avenant'), ('REGLEMENT_COPRO', 'Règlement de copropriété'), ('ASSURANCE', "Notice / attestation d'assurance"), ('CONVOCATION_AG', 'Convocation AG'), ('LETTRE', 'Lettre'), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeaseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Laisser vide pour ne pas expirer automatiquement.', null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_announcements', to='rental.lease')),
            ],
            options={
                'verbose_name': 'Annonce (portail locataire)',
                'verbose_name_plural': 'Annonces (portail locataire)',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='LeasePracticalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Texte libre (contacts, codes, horaires, consignes).')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_infos', to='rental.lease')),
            ],
            options={
                'verbose_name': 'Info pratique (portail)',
                'verbose_name_plural': 'Infos pratiques (portail)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumbing', 'Fuite / plomberie'), ('heating', 'Chauffage / eau chaude'), ('keys', 'Clés / accès'), ('other', 'Autre')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Reçue'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], default='RECEIVED', max_length=20)),
                ('landlord_reply', models.TextField(blank=True, help_text='Réponse visible par le locataire sur le portail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rental.lease')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rental.tenant')),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=rental.models._portal_maintenance_attachment_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rental.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Pièce jointe (intervention)',
                'verbose_name_plural': 'Pièces jointes (intervention)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('water', 'Eau'), ('electricity', 'Électricité'), ('gas', 'Gaz'), ('other', 'Autre')], max_length=20)),
                ('reading_date', models.DateField()),
                ('value', models.CharField(help_text='Index ou valeur relevée', max_length=80)),
                ('unit', models.CharField(blank=True, help_text='Ex. m³, kWh', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='rental.lease')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='rental.tenant')),
            ],
            options={
                'verbose_name': 'Relevé de compteur',
                'verbose_name_plural': 'Relevés de compteurs',
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateField()),
                ('method', models.CharField(choices=[('TRANSFER', 'Virement'), ('CARD', 'Carte bancaire'), ('SEPA', 'Prélèvement'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], default='TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence bancaire ou commentaire', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.rentinvoice')),
            ],
            options={
                'verbose_name': 'Paiement de loyer',
                'verbose_name_plural': 'Paiements de loyer',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
