# Generated by Django 5.2.12 on 2026-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_backfill_rentpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='portal_payment_url',
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_payment_bic',
            field=models.CharField(blank=True, help_text='Optionnel ; utile pour un virement international.', max_length=11, verbose_name='BIC / SWIFT'),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_payment_holder',
            field=models.CharField(blank=True, help_text='Nom affiché au locataire (optionnel).', max_length=200, verbose_name='Titulaire du compte'),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_payment_iban',
            field=models.CharField(blank=True, help_text='Coordonnées pour le virement du loyer, affichées sur le portail locataire (sans espaces ou avec espaces).', max_length=34, verbose_name='IBAN'),
        ),
    ]
