# Generated by Django 5.2.12 on 2026-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0030_lease_rib_replaces_portal_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le bailleur a accusé réception (visible par le locataire).', null=True),
        ),
    ]
