# Generated by Django 5.2.12 on 2026-03-28 21:23

import django.db.models.deletion
from django.db import migrations, models


def seed_maintenance_threads(apps, schema_editor):
    MR = apps.get_model("rental", "MaintenanceRequest")
    Msg = apps.get_model("rental", "MaintenanceThreadMessage")
    for mr in MR.objects.all():
        body_t = ((f"« {mr.title} »\n\n" if mr.title else "") + (mr.description or "")).strip()
        m = Msg.objects.create(
            maintenance_request_id=mr.pk,
            sender="tenant",
            body=body_t or "(Pas de description.)",
        )
        Msg.objects.filter(pk=m.pk).update(created_at=mr.created_at)
        if (mr.landlord_reply or "").strip():
            m2 = Msg.objects.create(
                maintenance_request_id=mr.pk,
                sender="landlord",
                body=mr.landlord_reply.strip(),
            )
            Msg.objects.filter(pk=m2.pk).update(created_at=mr.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0032_maintenance_status_remove_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('landlord', 'Bailleur'), ('tenant', 'Locataire')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='rental.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Message (fil intervention)',
                'verbose_name_plural': 'Messages (fil intervention)',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(seed_maintenance_threads, migrations.RunPython.noop),
    ]
