# Generated by Django 5.2.12 on 2026-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0034_propertytag_standard_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='volume_segment_key',
            field=models.CharField(choices=[('perso', 'Perso / essentiel'), ('actif', 'Actif / portefeuille'), ('pro', 'Pro / structure'), ('volume', 'Volume')], default='perso', help_text='Segment volume souscrit : plafond de biens actifs (non archivés) visibles pour ce compte.', max_length=20),
        ),
    ]
