from django.urls import path

from . import views, premium_views


app_name = "rental"

urlpatterns = [
    path("properties/", views.property_list, name="property_list"),
    path("properties/add/", views.property_create, name="property_create"),
    path("properties/<int:pk>/edit/", views.property_edit, name="property_edit"),
    path("properties/<int:pk>/delete/", views.property_delete, name="property_delete"),
    path("properties/<int:pk>/archive/", views.property_archive, name="property_archive"),
    path("properties/<int:pk>/unarchive/", views.property_unarchive, name="property_unarchive"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/add/", views.tenant_create, name="tenant_create"),
    path("tenants/<int:pk>/edit/", views.tenant_edit, name="tenant_edit"),
    path("tenants/<int:pk>/delete/", views.tenant_delete, name="tenant_delete"),
    path("tenants/<int:pk>/archive/", views.tenant_archive, name="tenant_archive"),
    path("tenants/<int:pk>/unarchive/", views.tenant_unarchive, name="tenant_unarchive"),
    path("leases/", views.lease_list, name="lease_list"),
    path("leases/add/", views.lease_create, name="lease_create"),
    path("leases/<int:pk>/", views.lease_detail, name="lease_detail"),
    path("leases/<int:pk>/edit/", views.lease_edit, name="lease_edit"),
    path("leases/<int:pk>/delete/", views.lease_delete, name="lease_delete"),
    path("leases/<int:pk>/archive/", views.lease_archive, name="lease_archive"),
    path("leases/<int:pk>/unarchive/", views.lease_unarchive, name="lease_unarchive"),
    path("leases/<int:pk>/signatures/", views.lease_request_signatures, name="lease_request_signatures"),
    path("leases/<int:pk>/signed.pdf", views.lease_signed_pdf, name="lease_signed_pdf"),
    path("leases/<int:pk>/fichier-joint.pdf", views.lease_attached_download, name="lease_attached_download"),
    path("leases/<int:lease_pk>/portal/info/", views.lease_portal_practical_add, name="lease_portal_practical_add"),
    path("portal/info/<int:pk>/delete/", views.lease_portal_practical_delete, name="lease_portal_practical_delete"),
    path("leases/<int:lease_pk>/portal/annonce/", views.lease_portal_announcement_add, name="lease_portal_announcement_add"),
    path("portal/annonce/<int:pk>/delete/", views.lease_portal_announcement_delete, name="lease_portal_announcement_delete"),
    path("portal/demande/<int:pk>/", views.maintenance_request_landlord_update, name="maintenance_request_landlord_update"),
    path(
        "portal/demande/<int:pk>/accuse-reception/",
        views.maintenance_request_acknowledge,
        name="maintenance_request_acknowledge",
    ),
    path("maintenance-requests/", views.maintenance_requests_list, name="maintenance_requests_list"),
    path("inspections/", views.inspection_list, name="inspection_list"),
    path("inspections/add/", views.inspection_create, name="inspection_create"),
    path("inspections/<int:pk>/", views.inspection_detail, name="inspection_detail"),
    path("inspections/<int:pk>/edit/", views.inspection_edit, name="inspection_edit"),
    path("inspections/<int:pk>/delete/", views.inspection_delete, name="inspection_delete"),
    path("inspections/<int:pk>/signatures/", views.inspection_request_signatures, name="inspection_request_signatures"),
    path("inspections/<int:pk>/signed.pdf", views.inspection_signed_pdf, name="inspection_signed_pdf"),
    path("inspections/<int:pk>/fichier-joint.pdf", views.inspection_attached_download, name="inspection_attached_download"),
    path("team/", views.team_page, name="team_page"),
    path("bank/", views.bank_account_list, name="bank_account_list"),
    path("bank/add/", views.bank_account_create, name="bank_account_create"),
    path("bank/<int:pk>/delete/", views.bank_account_delete, name="bank_account_delete"),
    path("bank/<int:account_pk>/", views.bank_transaction_list, name="bank_transaction_list"),
    path("bank/<int:account_pk>/import/", views.bank_import_csv, name="bank_import_csv"),
    path("bank/transaction/<int:transaction_pk>/match/", views.bank_match_transaction, name="bank_match_transaction"),
    path("bank/transaction/<int:transaction_pk>/unmatch/", views.bank_unmatch_transaction, name="bank_unmatch_transaction"),
    path("rentability-ai/", views.rentability_ai_page, name="rentability_ai"),
    path("api-access/", views.api_access_page, name="api_access"),
    path("mobile/", views.mobile_app_page, name="mobile_app"),
    path("reports/", premium_views.analytics_report, name="analytics_report"),
    path("reports/pdf/", premium_views.report_pdf, name="report_pdf"),
    path("reports/cashflow/", premium_views.cashflow_forecast, name="cashflow_forecast"),
    path("reminders/rules/", premium_views.reminder_rules_list, name="reminder_rules"),
    path("reminders/renewals/", premium_views.renewal_reminders_list, name="renewal_reminders"),
    path("documents/letters/", premium_views.letter_templates_list, name="letter_templates"),
    path("documents/letters/add/", premium_views.letter_template_create, name="letter_template_create"),
    path("documents/letters/<int:pk>/edit/", premium_views.letter_template_edit, name="letter_template_edit"),
    path("documents/letters/<int:pk>/delete/", premium_views.letter_template_delete, name="letter_template_delete"),
    path("documents/diagnostics/", premium_views.diagnostics_list, name="diagnostics_list"),
    path("documents/stored/add/", premium_views.stored_document_create, name="stored_document_create"),
    path("documents/stored/<int:pk>/edit/", premium_views.stored_document_edit, name="stored_document_edit"),
    path("documents/stored/<int:pk>/delete/", premium_views.stored_document_delete, name="stored_document_delete"),
    path("documents/stored/<int:pk>/file/", premium_views.stored_document_download, name="stored_document_download"),
    path("documents/stored/", premium_views.stored_documents_list, name="stored_documents"),
    path("property-dashboard/", premium_views.property_dashboard, name="property_dashboard"),
    path("portal/tenants/", premium_views.portal_tenant_list, name="portal_tenant_list"),
    path("tenants/<int:tenant_pk>/portal-link/", premium_views.portal_link_create, name="portal_link_create"),
    path("webhooks/", premium_views.webhooks_list, name="webhooks_list"),
    path("calendar.ics", premium_views.calendar_ics, name="calendar_ics"),
    path("audit/activity/", premium_views.activity_log_list, name="activity_log"),
    path("audit/export/", premium_views.data_export, name="data_export"),
    path("rents/", views.rentinvoice_list, name="rentinvoice_list"),
    path("export-comptabilite.csv", views.export_accounting_csv, name="export_accounting_csv"),
    path("leases/<int:lease_pk>/revise-rent/", views.rent_revise, name="rent_revise"),
    path("rents/<int:pk>/mark-paid/", views.rentinvoice_mark_paid, name="rentinvoice_mark_paid"),
    path("rents/<int:pk>/quittance.pdf", views.rentinvoice_quittance_pdf, name="rentinvoice_quittance_pdf"),
    path("rents/<int:pk>/quittance/<int:tenant_pk>.pdf", views.rentinvoice_quittance_tenant_pdf, name="rentinvoice_quittance_tenant_pdf"),
    path("rents/<int:pk>/send-quittance-per-tenant/", views.rentinvoice_send_quittance_per_tenant, name="rentinvoice_send_quittance_per_tenant"),
    path("lease-templates/", views.lease_template_list, name="lease_template_list"),
    path("lease-templates/add/", views.lease_template_create, name="lease_template_create"),
    path("lease-templates/<int:pk>/edit/", views.lease_template_edit, name="lease_template_edit"),
    path("lease-templates/<int:pk>/delete/", views.lease_template_delete, name="lease_template_delete"),
    path("inspection-templates/", views.inspection_template_list, name="inspection_template_list"),
    path("inspection-templates/add/", views.inspection_template_create, name="inspection_template_create"),
    path("inspection-templates/<int:pk>/edit/", views.inspection_template_edit, name="inspection_template_edit"),
    path("inspection-templates/<int:pk>/delete/", views.inspection_template_delete, name="inspection_template_delete"),
]

